# Generated by Django 3.1.3 on 2020-11-21 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('code', models.CharField(help_text='MCC + MNC code of the French operators', max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='NetworkCoveragePoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_coord', models.IntegerField()),
                ('y_coord', models.IntegerField()),
                ('has_2g', models.BooleanField()),
                ('has_3g', models.BooleanField()),
                ('has_4g', models.BooleanField()),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobile_coverage.operator')),
            ],
        ),
    ]
