# Generated by Django 3.1.3 on 2020-11-21 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_coverage', '0002_move_network_types_to_own_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_coord', models.IntegerField()),
                ('y_coord', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('house_number', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='networkcoveragepoint',
            name='x_coord',
        ),
        migrations.RemoveField(
            model_name='networkcoveragepoint',
            name='y_coord',
        ),
        migrations.AddField(
            model_name='networkcoveragepoint',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mobile_coverage.location'),
            preserve_default=False,
        ),
    ]
