# Generated by Django 3.1.3 on 2020-11-21 16:55

from django.db import migrations


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('mobile_coverage', '0003_move_to_own_model_and_enrich_location_information'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NetworkTypes',
            new_name='NetworkType',
        ),
    ]
